default_platform(:ios)

platform :ios do

  desc "Make a build for TestFlight"
  lane :assemble_ios_build do
    match(type: "appstore")
    gym(
      export_method: "app-store",
      workspace: "Serto.xcworkspace",
      scheme: "Serto",
      include_bitcode: true,
      include_symbols: true
    )
  end

  desc "Upload to Testflight"
  lane :upload_ios_testflight do
       match(type: "appstore")
       pilot(
         ipa: "./Serto.ipa",
         skip_submission: true,
         skip_waiting_for_build_processing: true
       )
  end

  desc "Build & Upload to Testflight"
  lane :build_and_upload do
    match(type: "appstore")
    gym(
      export_method: "app-store",
      workspace: "Serto.xcworkspace",
      scheme: "Serto",
      include_bitcode: true,
      include_symbols: true
    )
    pilot(
      ipa: "./Serto.ipa",
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )
  end  
end