default_platform(:ios)

platform :ios do

desc "Push a new beta build to TestFlight"
before_all do
  # Sets up fastlane match on Circle CI
  # for readonly code signing
  setup_circle_ci
end

desc "Build the iOS app"
lane :assemble_build do
  match(type: "appstore")
  gym(
    scheme: "Serto",
    export_method: "app-store",
    workspace: "Serto.xcworkspace",
    include_bitcode: true,
    include_symbols: true
    export_options: {
      provisioningProfiles: {
        "com.serto.wallet" => "match AppStore com.serto.wallet"
      }
    }
  )
end

desc "Deploy to TestFlight"
lane :deploy do
  # assemble_build
  upload_to_testflight
  # Includes the git tag commit message,
  # which has all the release notes
  # slack(message: "App successfully released!")
end